---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-sstate-x86-64
  namespace: tekton-pipelines
spec:
  steps:
    - name: setup
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        if [ -d poky ]; then
            rm -rf poky
        fi
        git clone git://git.yoctoproject.org/poky
      volumeMounts:
      - name: build
        mountPath: /workspace

    - name: build-sstate
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        pwd
        ls
        cd poky
        source oe-init-build-env build
        bitbake core-image-sato
      volumeMounts:
      - name: build
        mountPath: /workspace

