apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: sstate-build-test-setup-run-
  namespace: tekton-pipelines
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: sstate-build-test-setup
  timeout: 1h0m0s
  podTemplate:
    volumes:
    - name: build
      hostPath:
        path: /tekton/sstate-test
status:
  podName: ""
