apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: x86-64-sstate-pvc
  namespace: tekton-pipelines
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
