apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "yocto-sstate.fullname" . }}-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "yocto-sstate.fullname" . }}-nettools
            image: threexc/nettools
            args:
            - /bin/bash
            - -c
            - curl -X POST http://el-yocto-sstate-listener.tekton-pipelines.svc.cluster.local:8080
          restartPolicy: OnFailure
