apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "yocto-sstate.fullname" . }}-pipeline
  namespace: {{ .Release.Namespace }}
spec:
  tasks:
  - name: build-{{ include "yocto-sstate.fullname" . }}
    taskRef:
      name: build-{{ include "yocto-sstate.fullname" . }}
