apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "yocto-sstate.fullname" . }}-build-template
  namespace: {{ .Release.Namespace }}
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: {{ include "yocto-sstate.fullname" . }}-build-pipeline-run
    spec:
      pipelineRef:
        name: {{ include "yocto-sstate.fullname" . }}-build-pipeline
      timeout: "3h"
      podTemplate:
        volumes:
        - name: build
          hostPath:
            path: "{{ .Values.sstate.buildpath }}"
