apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: meta-python-container-pipeline
spec:
  tasks:
  - name: meta-python-build-patches
    taskRef:
      name: meta-python-build-patches
  - name: meta-python-run-ptest-container
    taskRef:
      name: meta-python-run-ptest-container
    runAfter:
      - meta-python-build-patches
