apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: poky-build-pipeline
  namespace: tekton-pipelines
spec:
  tasks:
  - name: poky-setup-workspace
    taskRef:
      name: poky-setup-workspace
  - name: poky-build
    runAfter:
     - poky-setup-workspace
    taskRef:
      name: poky-build
