---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: poky-build-run-
  namespace: tekton-pipelines
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: poky-build
  timeout: 2h0m0s
  podTemplate:
    volumes:
    - name: build
      hostPath:
        path: /tekton/data

status:
  podName: ""
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: poky-setup-workspace-run-
  namespace: tekton-pipelines
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: poky-setup-workspace
  timeout: 1h0m0s
  podTemplate:
    volumes:
    - name: build
      hostPath:
        path: /tekton/data
status:
  podName: ""
