apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: meta-openembedded-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git://git.openembedded.org/meta-openembedded

