---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yocto-meta-python-build
  namespace: yocto-build
spec:
  steps:
    - name: run-build
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        #ID=$RANDOM
        #BUILD="/workspace/build/build-$ID"
        #mkdir -p $BUILD
        #cd $BUILD
        #git clone --single-branch --branch $(branch) --depth 1 $(poky_repo)
        #git clone --single-branch --branch $(branch) --depth 1 $(meta-python_repo)
        #cd poky && source oe-init-build-env build
        git clone git://git.yoctoproject.org/poky 
        git clone git://git.openembedded.org/meta-openembedded
        (cd meta-openembedded && git checkout origin/master-next)
        cd poky && git checkout origin/master-next
        source oe-init-build-env build
        #echo "SSTATE_DIR = \"/workspace/build/sstate-cache-1020\"" >> conf/local.conf
        cat conf/bblayers.conf
        echo "BBLAYERS ?= \" \\
                /workspace/poky/meta \\
                /workspace/poky/meta-poky \\
                /workspace/poky/meta-yocto-bsp \\
                /workspace/meta-openembedded/meta-python \\
                /workspace/meta-openembedded/meta-oe \\
                /workspace/meta-openembedded/meta-networking \\
                /workspace/meta-openembedded/meta-filesystems \\
                /workspace/meta-openembedded/meta-webserver \\
                \"" > conf/bblayers.conf
        export LANG=en_US.UTF-8
        # get the latest python recipes and bitbake them
        (cd ../../meta-openembedded/ && git log --pretty=oneline --grep="python" origin/master..origin/master-next | awk '{print $2}' | tr -d :) | xargs bitbake
