apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: poky-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git://git.yoctoproject.org/poky

