---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-build-patches
  namespace: tekton-pipelines
spec:
  steps:
    - name: build-patches
      image: registry.hub.docker.com/threexc/yocto-builder:36
      workingDir: /workspace
      script: |
        #!/bin/bash
        # Add yocto-tekton repo to PATH
        export PATH="/workspace/yocto-tekton/meta-python/scripts:$PATH"
        # Get the latest python recipe changes and bitbake them using --diff-filter for Added (A), Copied (C), 
        # Modified (M), or Renamed (R) files. The filter character lines will always start with an upper-case 
        # letter (commit hashes don't use them). Also ignore deleted files (D flag to --diff-filter)
        COMMIT_LOG="$(get-recipe-changes.sh)"

        echo "${COMMIT_LOG}"

        # Exit cleanly if there is no difference between master and master-next
        if [ -z "${COMMIT_LOG}" ]; then
            echo "No difference between master and master-next branches. Exiting..."
            exit 0
        fi
        
        RECIPE_NAME=""

        cd poky && source oe-init-build-env build
        export LANG=en_US.UTF-8

        RECIPE_LIST=$(get-bitbake-list.sh "${COMMIT_LOG}")

        echo ${RECIPE_LIST} | xargs bitbake
        echo "The following list was sent to bitbake: "
        for recipe in $RECIPE_LIST; do
            echo $recipe
        done
      volumeMounts:
      - name: build
        mountPath: /workspace
