apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: yp-dev-day-virtualization-build-run-
  namespace: tekton-pipelines
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: yp-dev-day-virtualization-build
  timeout: 5h0m0s
  podTemplate:
    volumes:
    - name: build
      hostPath:
        path: /tekton/data

status:
  podName: ""
