apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: yp-dev-day-virtualization-log-run-
  namespace: tekton-pipelines
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: yp-dev-day-virtualization-log
  timeout: 0h15m0s
  podTemplate:
    volumes:
    - name: log
      hostPath:
        path: /tekton/data/logs

status:
  podName: ""
