---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yp-dev-day-virtualization-testimage
  namespace: tekton-pipelines
spec:
  steps:
    - name: build-testimages
      image: registry.hub.docker.com/kasproject/kas
      args: 
      workingDir: /workspace/yp-dev-day_virtualization
      script: |
        #!/bin/bash -xe
        bitbake meta-python2-ptest-image
      volumeMounts:
      - name: build
        mountPath: /workspace
    - name: run-testimage
      image: registry.hub.docker.com/kasproject/kas
      args:
      workingDir: /workspace/yp-dev-day_virtualization
      script: |
        #!/bin/bash -xe
        source oe-init-build-env build
        export LANG=en_US.UTF-8
        bitbake -c testimage meta-python2-ptest-image
      volumeMounts:
      - name: build
        mountPath: /workspace
