---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-setup-container-conf
  namespace: tekton-pipelines
spec:
  steps:
    - name: setup-conf
      image: registry.hub.docker.com/threexc/yocto-builder:33
      workingDir: /workspace
      script: |
        #!/bin/bash
        if [ ! -d poky/build/conf/ ]; then
          cd poky && source oe-init-build-env build
          echo "BBLAYERS ?= \" \\
                  /workspace/poky/meta \\
                  /workspace/poky/meta-poky \\
                  /workspace/poky/meta-yocto-bsp \\
                  /workspace/meta-openembedded/meta-python \\
                  /workspace/meta-openembedded/meta-oe \\
                  /workspace/meta-openembedded/meta-networking \\
                  /workspace/meta-openembedded/meta-filesystems \\
                  /workspace/meta-openembedded/meta-webserver \\
                  \"" > conf/bblayers.conf
          # Add required elements to local.conf for ptest image build
          echo "INHERIT += \"testimage\"" >> conf/local.conf
          echo "TEST_SUITES = \"ping ssh rpm ptest\"" >> conf/local.conf
          echo "DISTRO_FEATURES_append = \" ptest\"" >> conf/local.conf
          echo "DISTRO_FEATURES_append = \" ptest systemd pam\"" >> conf/local.conf
          echo "FORTRAN_forcevariable = \",fortran\"" >> conf/local.conf
          echo "IMAGE_FSTYPES = \"tar.gz container\"" >> conf/local.conf
          echo "PREFERRED_PROVIDER_virtual/kernel = \"linux-dummy\"" >> conf/local.conf
        fi
      volumeMounts:
      - name: build
        mountPath: /workspace
