apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "yocto-sstate.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yocto-sstate.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.pv.path }}"
