apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "yocto-sstate.labels" . | nindent 4 }}
  name: {{ include "yocto-sstate.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
