apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yocto-sstate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yocto-sstate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yocto-sstate.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "yocto-sstate.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-pvc
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
          name: http-server
          protocol: TCP
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: {{ .Chart.Name }}-pvc
      volumes:
        - name: {{ .Chart.Name }}-pvc
          persistentVolumeClaim:
           claimName: {{ .Chart.Name }}-pvc
