---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: meta-multimedia-cronjob
  namespace: tekton-pipelines
spec:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meta-multimedia-nettools
            image: threexc/nettools
            args:
            - /bin/bash
            - -c
            - |
              curl -X POST \
              http://el-meta-openembedded-listener.tekton-pipelines.svc.cluster.local:8080 \
              -H 'Content-Type: application/json' \
              -d "{ \"layer\": \"meta-multimedia\"
              }"
          restartPolicy: OnFailure
