apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: meta-openembedded-pipelinerun-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: meta-openembedded-pipeline
  timeout: 1h30m0s
  params:
  - name: layer
    value: meta-python
  - name: repo-dir
    value: meta-openembedded
  podTemplate:
    volumes:
    - name: meta-openembedded-pvc
      persistentVolumeClaim:
        claimName: meta-openembedded-pvc
