---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: meta-python-cronjob
  namespace: tekton-pipelines
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meta-python-nettools
            image: threexc/nettools
            args:
            - /bin/bash
            - -c
            - curl -X POST http://el-meta-python-listener.tekton-pipelines.svc.cluster.local:8080
          restartPolicy: OnFailure
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: meta-python-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  serviceType: NodePort
  triggers:
    - name: meta-python-build
      template:
        ref: meta-python-build-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: meta-python-build-template
  namespace: tekton-pipelines
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: meta-python-build-pipeline-run-
    spec:
      pipelineRef:
        name: meta-python-build-pipeline
      timeout: "3h"
      podTemplate:
        volumes:
        - name: build
          hostPath:
            path: /tekton/data
