---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-build-ptest-vm
spec:
  steps:
    - name: build-ptest-image
      image: registry.hub.docker.com/threexc/yocto-builder:34
      workingDir: /workspace
      script: |
        #!/bin/bash -e
        # Add yocto-tekton repo to PATH
        export PATH="/workspace/yocto-tekton/meta-python/scripts:$PATH"

        # Move into poky directory, remove old conf, source build
        cd poky && source oe-init-build-env build
        export LANG=en_US.UTF-8
        
        bitbake meta-python-ptest-image
        echo "FROM scratch" > /workspace/poky/build/tmp/deploy/images/qemux86-64/Dockerfile
        echo "ADD meta-python-ptest-image-qemux86-64.tar.gz /" >> /workspace/poky/build/tmp/deploy/images/qemux86-64/Dockerfile
      volumeMounts:
      - name: build
        mountPath: /workspace
