apiVersion: apps/v1
kind: Deployment
metadata:
  name: yocto-sstate
  namespace: tekton-pipelines
  labels:
    app: yocto-sstate
spec:
  selector:
    matchLabels:
      app: yocto-sstate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yocto-sstate
    spec:
      containers:
      - name: yocto-sstate-pvc
        image: httpd
        ports:
        - containerPort: 80
          name: http-server
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: yocto-sstate-pvc
      volumes:
        - name: yocto-sstate-pvc
          persistentVolumeClaim:
           claimName: yocto-sstate-pvc
