apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: yocto-sstate
  name: yocto-sstate
  namespace: tekton-pipelines
spec:
  ports:
  - name: yocto-sstate-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: yocto-sstate
  type: NodePort
status:
  loadBalancer: {}
