apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: sstate-build-pipeline-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: sstate-build-pipeline
  timeout: 1h0m0s
  podTemplate:
    volumes:
    - name: build
      hostPath:
        path: /forge1/sstate
status: {}
