---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sstate-build
  namespace: tekton-pipelines
spec:
  steps:
    - name: setup-repo
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        if [ -d poky ]; then
            cd poky && git pull --rebase
        else
            git clone git://git.yoctoproject.org/poky
        fi
      volumeMounts:
      - name: build
        mountPath: /workspace

    - name: sstate-build
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        cd poky
        source oe-init-build-env build
        bitbake core-image-minimal && bitbake core-image-full-cmdline && bitbake core-image-sato && bitbake core-image-sato-sdk
      volumeMounts:
      - name: build
        mountPath: /workspace

