---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: meta-python-cronjob
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meta-python-nettools
            image: threexc/nettools
            args:
            - /bin/bash
            - -c
            - curl -X POST http://el-meta-python-listener.meta-python.svc.cluster.local:8080 -H 'Content-Type: application/json' -d '{}'
          restartPolicy: OnFailure
