apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: meta-python-build-pipeline
  namespace: tekton-pipelines
spec:
  tasks:
  - name: meta-python-build
    taskRef:
      name: meta-python-build
