---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-build
  namespace: tekton-pipelines
spec:
  steps:
    - name: run-build
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace/poky
      script: |
        #!/bin/bash -xe
        source oe-init-build-env build
        export LANG=en_US.UTF-8
        # get the latest python recipes and bitbake them
        RECIPES=$(cd ../../meta-openembedded/ && git log --pretty=oneline --grep="python" origin/master..origin/master-next | awk '{print $2}' | tr -d :)
        bitbake $RECIPES
      volumeMounts:
      - name: build
        mountPath: /workspace

