---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-build
  namespace: tekton-pipelines
spec:
  steps:
    - name: run-build
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace/poky
      script: |
        #!/bin/bash -xe
        source oe-init-build-env build
        cat conf/bblayers.conf
        echo "BBLAYERS ?= \" \\
                /workspace/poky/meta \\
                /workspace/poky/meta-poky \\
                /workspace/poky/meta-yocto-bsp \\
                /workspace/meta-openembedded/meta-python \\
                /workspace/meta-openembedded/meta-oe \\
                /workspace/meta-openembedded/meta-networking \\
                /workspace/meta-openembedded/meta-filesystems \\
                /workspace/meta-openembedded/meta-webserver \\
                \"" > conf/bblayers.conf
        echo "SSTATE_MIRRORS = \"file://.* http://httpd-sstate.tekton-pipelines/poky/build/sstate-cache/PATH\"" >> conf/local.conf
        echo "USER_CLASSES += \"buildstats buildstats-summary\"" >> conf/local.conf
        export LANG=en_US.UTF-8
        # get the latest python recipes and bitbake them
        RECIPES=$(cd ../../meta-openembedded/ && git log --pretty=oneline --grep="python" origin/master..origin/master-next | awk '{print $2}' | tr -d :)
        bitbake $RECIPES
      volumeMounts:
      - name: build
        mountPath: /workspace

