---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: meta-python-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meta-python-nettools
            image: registry.hub.docker.com/threexc/nettools
            command: ["/bin/bash"]
            args: ["-c", "curl -X POST http://el-meta-python-listener.meta-python.svc.cluster.local:8080 -H 'Content-Type: application/json' -d '{\"trigger_template\":\"nightly\"}'"]
          restartPolicy: OnFailure
