apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: meta-python-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meta-python-nettools
            image: threexc/nettools
            args:
            - /bin/bash
            - -c
            - curl -X POST http://el-meta-python-listener.tekton-pipelines.svc.cluster.local:8080
          restartPolicy: OnFailure
