apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  creationTimestamp: null
  generateName: meta-python-setup-workspace-run-
  namespace: tekton-pipelines
spec:
  inputs: {}
  outputs: {}
  serviceAccountName: ""
  taskRef:
    name: meta-python-setup-workspace
  timeout: 1h0m0s
  podTemplate:
    volumes:
    - name: build
      hostPath:
        path: /tekton/data
status:
  podName: ""
