apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: meta-python-nightly
spec:
  tasks:
  - name: update-workspace
    taskRef:
      name: meta-python-update-workspace
  - name: setup-conf
    taskRef:
      name: meta-python-setup-conf
    runAfter:
      - update-workspace
  - name: build-patches
    taskRef:
      name: meta-python-build-patches
    runAfter:
      - setup-conf
  - name: build-packagegroup
    taskRef:
      name: meta-python-build-packagegroup
    runAfter:
      - build-patches
  - name: build-ptest-container
    taskRef:
      name: meta-python-build-ptest-container
    runAfter:
      - build-packagegroup
  - name: run-ptest
    taskRef:
      name: meta-python-run-ptest
    runAfter:
      - build-ptest-container
