apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: meta-python-build-pipeline-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: meta-python-build-pipeline
  timeout: 1h0m0s
  podTemplate:
    volumes:
    - name: meta-python-pvc
      persistentVolumeClaim:
        claimName: meta-python-pvc
status: {}
