apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meta-python-pvc
  namespace: tekton-pipelines
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
