---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-setup-workspace
  namespace: tekton-pipelines
spec:
  steps:
    - name: create-workspace
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        if [ ! -d poky ]; then
            git clone git://git.yoctoproject.org/poky
            git clone git://git.openembedded.org/meta-openembedded
        fi
      volumeMounts:
      - name: build
        mountPath: /workspace

    - name: update-workspace
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        (cd poky && git checkout master-next && git pull --rebase)
        (cd meta-openembedded && git checkout master-next && git pull --rebase)
      volumeMounts:
      - name: build
        mountPath: /workspace

