---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python-setup-workspace
  namespace: tekton-pipelines
spec:
  steps:
    - name: clear-old-workspace
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        if [ -d "poky/build/tmp" ]; then
            rm -rf poky/build/tmp
        fi
      volumeMounts:
      - name: build
        mountPath: /workspace
    - name: create-workspace
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        if [ ! -d "poky" ]; then
            git clone git://git.yoctoproject.org/poky
        fi

        if [ ! -d "meta-openembedded" ]; then
            git clone git://git.openembedded.org/meta-openembedded
        fi
        
        if [ ! -d "logs/qemux86-64" ]; then
            mkdir -p logs/qemux86-64
        fi
      volumeMounts:
      - name: build
        mountPath: /workspace

    - name: update-workspace
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        (cd poky && git checkout master && git pull --rebase)
        (cd meta-openembedded && git checkout master-next && git pull --rebase)
      volumeMounts:
      - name: build
        mountPath: /workspace
    - name: setup-conf
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace
      script: |
        #!/bin/bash -xe
        if [ ! -d poky/build/conf/ ]; then
          cd poky && source oe-init-build-env build
          echo "BBLAYERS ?= \" \\
                  /workspace/poky/meta \\
                  /workspace/poky/meta-poky \\
                  /workspace/poky/meta-yocto-bsp \\
                  /workspace/meta-openembedded/meta-python \\
                  /workspace/meta-openembedded/meta-oe \\
                  /workspace/meta-openembedded/meta-networking \\
                  /workspace/meta-openembedded/meta-filesystems \\
                  /workspace/meta-openembedded/meta-webserver \\
                  \"" > conf/bblayers.conf
          echo "SSTATE_MIRRORS = \"file://.* http://yocto-sstate.tekton-pipelines/poky/build/sstate-cache/PATH\"" >> conf/local.conf
          echo "USER_CLASSES += \"buildstats buildstats-summary\"" >> conf/local.conf
          echo "DISTRO_FEATURES_append = \" systemd pam\"" >> conf/local.conf
          echo "DISTRO_FEATURES_BACKFILL_CONSIDERED += \"sysvinit\"" >> conf/local.conf
          echo "VIRTUAL-RUNTIME_init_manager = \"systemd\"" >> conf/local.conf
          echo "VIRTUAL-RUNTIME_initscripts = \"systemd-compat-units\"" >> conf/local.conf
          echo "INHERIT += \" testimage\"" >> conf/local.conf
          echo "QEMU_USE_SLIRP = \"1\"" >> conf/local.conf
        fi
      volumeMounts:
      - name: build
        mountPath: /workspace

