---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: meta-python-nightly-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: meta-python-nightly-
    spec:
      pipelineRef:
        name: meta-python-nightly
      timeout: "3h"
      podTemplate:
        volumes:
        - name: build
          hostPath:
            path: /workspace/tekton/pipelines/meta-python
