---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meta-python-pv
  namespace: tekton-pipelines
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tekton/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meta-python-pvc
  namespace: tekton-pipelines
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
