---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python2-build
  namespace: tekton-pipelines
spec:
  steps:
    - name: run-build
      image: registry.hub.docker.com/threexc/yocto-builder
      workingDir: /workspace/poky
      script: |
        #!/bin/bash -xe
        source oe-init-build-env build
        export LANG=en_US.UTF-8
        # get the latest python2 patches from patchwork and bitbake them
        patchwork list -p oe -s New "[meta-python2"
        echo "The following patches were not addressed: "
        echo "${UNBUILT_LOG}"
      volumeMounts:
      - name: build
        mountPath: /workspace

