apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: meta-python-cronjob
  namespace: tekton-pipelines
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meta-python2-nettools
            image: threexc/nettools
            args:
            - /bin/bash
            - -c
            - curl -X POST http://el-meta-python2-listener.tekton-pipelines.svc.cluster.local:8080
          restartPolicy: OnFailure
