---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python2-testimage
  namespace: tekton-pipelines
spec:
  steps:
    - name: build-testimage
      image: registry.hub.docker.com/threexc/yocto-builder
      args: 
      workingDir: /workspace/poky
      script: |
        #!/bin/bash -xe
        source oe-init-build-env build
        export LANG=en_US.UTF-8
        bitbake meta-python2-ptest-image
      volumeMounts:
      - name: build
        mountPath: /workspace
    - name: run-testimage
      image: registry.hub.docker.com/threexc/yocto-builder
      args:
      workingDir: /workspace/poky
      script: |
        #!/bin/bash -xe
        source oe-init-build-env build
        export LANG=en_US.UTF-8
        bitbake -c testimage meta-python2-ptest-image
      volumeMounts:
      - name: build
        mountPath: /workspace
