---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: meta-python2-testimage
  namespace: tekton-pipelines
spec:
  resources:
      outputs:
        - name: workspace
          resourceref:
            testimage-ptest-image
  steps:
    - name: build-testimage
      image: registry.hub.docker.com/threexc/yocto-builder
      args: 
      workingDir: /workspace/meta-python2
      script: |
        #!/bin/bash -xe
        kas build kas/meta-python2-ptest-image.yml
      volumeMounts:
      - name: build
        mountPath: /workspace
    - name: run-testimage
      image: registry.hub.docker.com/threexc/yocto-builder
      args:
      workingDir: /workspace/meta-python2
      script: |
        #!/bin/bash -xe
        kas build -c testimage kas-meta-python2-ptest-image.yml
      volumeMounts:
      - name: build
        mountPath: /workspace

