---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: meta-python-patch-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: meta-python-patch-build
      template:
        ref: meta-python-patch-build-template

